### ISSUE TITLE
Why do I get this error when I start the application

### ISSUE THREAD

**Issue by bycod-android** [ExpediaGroup/graphql-kotlin#1923] opened 2024-02-02 14:47 UTC
![Снимок экрана 2024-02-02 174414](https://github.com/ExpediaGroup/graphql-kotlin/assets/64665423/8822391b-a4a4-485b-8105-f5956d3c6965)

**Comment by samuelAndalon** [comment] 2024-02-02 16:17
Hello, without a repo link, a zip file of a project with a reproduction of the issue is hard to tell.

check if your server started.

**Comment by dariuszkuc** [comment] 2024-02-20 18:38
Please provide a link to github repository that reproduces the issue. Closing this as it is currently impossible to diagnose what caused your startup issue.

**Closed by dariuszkuc** 2024-02-20 18:38 UTC
