### ISSUE TITLE
Optional fields that default to not-null

### ISSUE THREAD

**Issue by curtiscook** [ExpediaGroup/graphql-kotlin#1885] opened 2023-11-17 20:04 UTC
**Library Version**
latest

**Describe the bug**
It's not possible to make an argument non-nullable and optionally provided

Required to work
```
publish: Boolean? = null,
```
(and then set to default in the mutation function)

Expected to work
```
publish: Boolean = false,
```
Result:
```
Field <field name> argument "publish" of type "Boolean!" is required, but it was not provided
```

**Comment by dariuszkuc** [comment] 2023-11-17 20:32
Hello 👋 
Unfortunately default arguments are not supported due to the reflections limitations, see https://github.com/ExpediaGroup/graphql-kotlin/issues/53

Closing as duplicate of the #53

**Closed by dariuszkuc** 2023-11-17 20:32 UTC
Labels: type: bug
