### ISSUE TITLE
Include Fragments during client code generation

### ISSUE THREAD

**Issue by TSwifts** [ExpediaGroup/graphql-kotlin#1536] opened 2022-09-05 14:18 UTC
**Is your feature request related to a problem? Please describe.**
The client code generator appears to be ignoring fragments contained in query files at the moment. This can lead to unnecessary duplicate query code as repeated parts of the query can't be extracted into a fragment and be reused.

**Describe the solution you'd like**
The client code generator should treat fragments as part of the query and generate code containing all projections and entities of a fragment.

**Describe alternatives you've considered**
Under "Additional context" please follow the link to a small project I've created to demonstrate my problem description. I'm aware that the demo project seems a bit "constructed" and that an easy solution for this particular case would be to simply pull the "SubAttributes" into the "Attributes"' interface. 
This demo project is derived from an actual project I'm working on, though and that project's API is much more complex. Simply moving fields to interfaces is not possible for every case there.

**Additional context**
Here is the link to my demo project: [GraphQL-Kotlin-Client-Fragments](https://github.com/TSwifts/GraphQL-Kotlin-Client-Fragments)

**Comment by dariuszkuc** [comment] 2022-09-06 16:16
Hello 👋 
Client code generator is aware fragments and includes their selection set in the generated objects. It currently does not generate separate objects for fragments. 

Closing this issue as it is a duplicate of https://github.com/ExpediaGroup/graphql-kotlin/issues/1245

**Closed by dariuszkuc** 2022-09-06 16:16 UTC
Labels: type: enhancement

**Comment by TSwifts** [comment] 2022-09-07 06:27
Indeed I missed the fragment being included in the generated query and the similarity to the already open issue.
Thank you very much for the response! 👍 🙂
