### ISSUE TITLE
jackson deserialisation error

### ISSUE THREAD

**Issue by mmaryo** [ExpediaGroup/graphql-kotlin#895] opened 2020-10-02 13:05 UTC
Hello 

**Library Version**
Kotlin 1.4.0
Quarkus 1.8.1.Final
graphql-kotlin 4.0.0-alpha.4

**Describe the bug**
There is a bug while deserialize response with Jackson 

**To Reproduce**

There an exemple in the repo https://github.com/mmaryo/test-graphql-kotlin

This is a simple Graphql

```
type Query {
    pairs: [Pair!]!
}
query UniswapPairTop100Query {
    pairs {
        id
    }
}
type Pair {
    id: ID!
}
```

And the code 
(run the classe in test folder)

```
val client = (URL(apiUrl))
runBlocking {
    val pairsTop100 = uniswapClient.pairsTop100()
    println(pairsTop100)
}
```

And the result 

```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Strange Map type java.util.Map: cannot determine type parameters
 at [Source: (String)"{"errors":[{"locations":[{"line":1,"column":1}],"message":"Unexpected `type[Name]`\nExpected `{`, `query`, `mutation`, `subscription` or `fragment`"}]}"; line: 1, column: 1]

	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:62)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:227)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:143)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:414)

```

**Comment by dariuszkuc** [comment] 2020-10-02 14:25
Sounds like an issue with Jackson -> see https://github.com/quarkusio/quarkus/issues/11549, https://github.com/FasterXML/jackson-module-kotlin/issues/356 and https://github.com/ExpediaGroup/graphql-kotlin/issues/850

Try explicitly downgrading Jackson to `2.11.1` that might help.

Closing as duplicate of https://github.com/ExpediaGroup/graphql-kotlin/issues/850

**Closed by dariuszkuc** 2020-10-02 14:25 UTC
Labels: type: bug
