### ISSUE TITLE
Defaulting values do not work when using it on child objects

### ISSUE THREAD

**Issue by JustinSchwarzwald** [ExpediaGroup/graphql-kotlin#1503] opened 2022-08-02 23:37 UTC
**Library Version**
graphql-kotlin-spring-server version "6.1.0"
org.springframework.boot version "2.7.2"

**Describe the bug**
When using a default argument for a child object, the default parameter is given "null" instead of a default value.
 
**To Reproduce**
Steps to reproduce the behavior. Please provide:
For a depth of 1
```
@Component
class DefaultValueQueryDepth1 : Query {
    suspend fun returnTrueIfModelValueDefaults(queryModel: QueryModel?): Boolean {
        return queryModel?.value == "defaultValue"
    }
}
data class QueryModel(val value: String? = "defaultValue")
```
For a depth of 2
```
@Component
class DefaultValueQueryDepth2 : Query {
    suspend fun returnTrueIfChildValueDefaults(parentQueryModel: ParentQueryModel): Boolean {
        return parentQueryModel.childQueryModel?.value == "defaultValue"
    }
}
data class ParentQueryModel(val childQueryModel: ChildQueryModel? = ChildQueryModel("defaultValue"))
data class ChildQueryModel(val value: String? = "defaultValue")
```
![image](https://user-images.githubusercontent.com/43459254/182494203-9077bcba-9293-4072-8783-520c41711537.png)

Please also see the following repo for the bug : https://github.com/JustinSchwarzwald/GraphQLDefaultingValuesBug

**Expected behavior**
The child object should receive the default value that is specified.

**Comment by JustinSchwarzwald** [comment] 2022-08-02 23:38
linking default arguments
https://github.com/ExpediaGroup/graphql-kotlin/pull/981

**Comment by samuelAndalon** [comment] 2022-08-03 02:05
I think this  issue was caused by stop using object mapper to serialize arguments into classes, was able to repro, will check how to fix it. 
The reason is that we use reflections to check the arguments of the primary constructor and we map them against the fields of the objects provided as query argument, so in this case `childQueryModel` does not exists and is evaluated to null, which is passed to the primary constructor of `ParentQueryModel`

**Comment by samuelAndalon** [comment] 2022-08-05 19:34
fix for this will be included in next release

**Closed** 2022-08-09 16:16 UTC
Labels: type: bug, module: generator

**Comment by cryptoki** [comment] 2022-08-15 10:40
@samuelAndalon is there a time frame for the next release, including the fix / upgrade?

**Comment by samuelAndalon** [comment] 2022-08-15 17:07
@cryptoki  We will release a minor version in the following days.

**Comment by samuelAndalon** [comment] 2022-08-16 19:00
https://github.com/ExpediaGroup/graphql-kotlin/releases/tag/6.2.0

**Comment by cryptoki** [comment] 2022-08-16 19:57
@samuelAndalon 👍 thanks. first service upgraded, tests successful and runs with `graphql-kotlin 6.2.0` 🥳
