### ISSUE TITLE
Duplicated generated classes when generating via schema file

### ISSUE THREAD

**Issue by VladGaluska** [ExpediaGroup/graphql-kotlin#1868] opened 2023-10-17 21:28 UTC
Library Version: 7.0.1

When I generate the classes for a schema and its operations, I get duplicated classes for same fragments/types.
I.e:
```
package com.baeldung.graphql.client.generated.conferencebyidquery

import com.expediagroup.graphql.client.Generated
import kotlin.Int
import kotlin.String
import kotlin.collections.List

@Generated
public data class Conference(
  public val id: Int? = null,
  public val name: String,
  public val attendees: List<Int>,
  public val attendeeObjects: List<Attendee>,
)
```
```
package com.baeldung.graphql.client.generated.saveorcreateconferencemutation

import com.expediagroup.graphql.client.Generated
import kotlin.Int
import kotlin.String
import kotlin.collections.List

@Generated
public data class Conference(
  public val id: Int? = null,
  public val name: String,
  public val attendees: List<Int>,
  public val attendeeObjects: List<Attendee>,
)
```

To reproduce, see project here:
https://github.com/VladGaluska/kotlin-tutorials/tree/KTLN-585/kotlin-ktor
It contains both a server and a client in the same project. The schema generated is the one taken from the server.

I don't see why it generates different classes for every single operation, i.e. conference_by_id_query and save_or_create_conference_mutation

**Comment by dariuszkuc** [comment] 2023-10-17 21:40
Thanks for raising this but this is a duplicate of https://github.com/ExpediaGroup/graphql-kotlin/issues/1245

**Closed by dariuszkuc** 2023-10-17 21:40 UTC
Labels: type: bug
