### ISSUE TITLE
Declared defaults disappear from schema

### ISSUE THREAD

**Issue by icon1123** [ExpediaGroup/graphql-kotlin#1119] opened 2021-04-19 20:39 UTC
Library Version
4.0.0-rc.1

Describe the bug
Declared defaults disappear from schema

To Reproduce
[Query Class]
@Component
class BbsMdBoardQuery(
    private val boardService: BbsMdBoardService
) : Query {

    fun bbdMdBoardPage(
        keyword: String?,
        page: Int = 1,
        size: Int = 12,
        sortField: BbsMdBoardSortField = BbsMdBoardSortField.NAME,
        asc: Boolean = true
    ): BbsMdBoardPart { ... }

}

[Scheme]
type Query @extends {
  _service: _Service
  bbdMdBoardPage(asc: Boolean!, keyword: String, page: Int!, size: Int!, sortField: BbsMdBoardSortField!): BbsMdBoardPart!
}

Expected behavior
[Scheme]
type Query @extends {
  _service: _Service
  bbdMdBoardPage(asc: Boolean! = true, keyword: String, page: Int! = 1, size: Int! = 12, sortField: BbsMdBoardSortField! = NAME): BbsMdBoardPart!
}

**Comment by dariuszkuc** [comment] 2021-04-19 20:42
Duplicate of https://github.com/ExpediaGroup/graphql-kotlin/issues/53

**Closed by dariuszkuc** 2021-04-19 20:42 UTC
Labels: type: bug
