### ISSUE TITLE
Unable to use Reactor in an async model

### ISSUE THREAD

**Issue by johanflint** [ExpediaGroup/graphql-kotlin#596] opened 2020-02-08 11:16 UTC
Thank you for building this elegant library, it seems to suit our needs well as it written in Kotlin, runs on Spring Boot Webflux and offers a code-first approach to GraphQL.

Our architecture is based on reactive streams using Reactor, so I'm happy to [read](https://expediagroup.github.io/graphql-kotlin/docs/execution/async-models) that the library supports that. However, I cannot seem to get it to work properly.

As an example I wrote the following:
```kotlin
@Component
class MyAwesomeQuery : Query {
    fun widgetById(id: Int): Mono<Widget> = Mono.just(Widget(id, "value"))
}

data class Widget(val id: Int, val value: String)
```

If I execute the a query including the `id` and `value` I get the following response:
```json
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable type: 'Int' within parent 'Widget' (/widgetById/id)",
      "path": [
        "widgetById",
        "id"
      ],
      "errorType": "DataFetchingException",
      "locations": null,
      "extensions": null
    }
  ]
}
```

However, if I query only the `value`, I get this:
```json
{
  "data": {
    "widgetById": {
      "value": "Widget(id=7, value=value)"
    }
  }
}
```

The reason is that the `Mono` is not unwrapped properly but returned as is (`value` is the property in which the value of `Mono` is stored).

Here is the incomplete `SchemaGeneratorHooks` that I tried, but without this I'm still getting the same response.

```kotlin
@SpringBootApplication
class DomainModelApplication {
	@Bean
	fun hooks() = MonadHooks()
}

class MonadHooks : SchemaGeneratorHooks {
    override fun willResolveMonad(type: KType): KType = when (type.classifier) {
        Mono::class -> type.arguments.firstOrNull()?.type
        else -> type
    } ?: type
}
```

I know that I can return a `CompletableFuture<Widget>` instead, but that seems to be [blocking](https://stackoverflow.com/questions/58504527/is-mono-tofuture-blocking) and it is nice to use the same abstraction (Reactor) everywhere. 

What am I doing wrong here? Thank you for taking the time to read my question!

**Comment by dariuszkuc** [comment] 2020-02-08 18:03
Thanks for raising this. It appears that with recent refactorings we broke monad support, i.e.

```kotlin
fun delayedEchoUsingReactorMono(msg: String, delaySeconds: Int): Mono<String> = Mono.just(msg)
```

returns

```json
{
  "data": {
    "delayedEchoUsingReactorMono": "MonoJust"
  }
}
```

instead of actual passed in message.

**Comment by johanflint** [comment] 2020-02-08 20:16
I'm glad to hear I didn't misconfigure anything. So if I understand you correctly, Reactor is supported out of the box without any custom configuration?

**Comment by dariuszkuc** [comment] 2020-02-08 20:25
> I'm glad to hear I didn't misconfigure anything. So if I understand you correctly, Reactor is supported out of the box without any custom configuration?

Reactor (as well as RxJava2) support is added through schema hook (as per example) but unfortunately it is currently broken.

**Comment by smyrick** [comment] 2020-02-08 21:08
It seems that since we removed the [`DataFetcherExecutionPredicate`](https://github.com/ExpediaGroup/graphql-kotlin/blob/1.4.2/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/DataFetcherExecutionPredicate.kt)
we no longer have a option to convert retrieve the value after execution.

`willResolveMonad` will tell the generator how to interpret the class info for building the schema but we still need to provide more info on how to actually retrieve the value to return. Instead of adding the back, I think a better approach is to add a new method to the hooks that will allow you to convert the value in the same fashion

**Comment by dariuszkuc** [comment] 2020-02-08 21:20
@smyrick since this logic needs to be applied at runtime I don't think it should be part of the schema generator hooks as those are used to generate the schema. We recently opened up data fetcher - maybe we should allow some extension there?

**Comment by smyrick** [comment] 2020-02-08 22:13
@dariuszkuc Yea, good point the `SchemaGeneratorHooks` are not great for execution hooks. Do we need a whole separate hooks class for execution?

The issue is that the schema generator `willResolveMonad` needs to have similar logic for all the custom types you want to add. I am creating a draft PR that adds them to the existing hook so we can give more context.

**Comment by smyrick** [comment] 2020-02-08 22:18
I have started a new draft PR here to see what adding them to the existing hooks looks like: https://github.com/ExpediaGroup/graphql-kotlin/pull/597

**Comment by dariuszkuc** [comment] 2020-02-10 05:40
I don't think that modifying existing `SchemaGeneratorHooks` is a proper fix - i.e. those hooks are used to customize schema generation logic and we need to update the runtime logic. 

Similarly creating custom execution hooks is somewhat duplicating what [instrumentation](https://www.graphql-java.com/documentation/v14/instrumentation/) is supposed to do. Unfortunately it appears that current `graphql-java` implementation will not work in this case. 

Doing custom execution hook that is tied to a `FunctionDataFetcher` might do the trick but assumption that it would run could easily be broken if one were to create custom `DataFetcher` (e.g. one use case is to provide custom coroutine context over default one). We could technically make it somewhat more robust by updating `KotlinDataFetcherFactoryProvider` to return an instance of some custom `KotlinDataFetcherFactory` (that creates `FunctionDataFetcher` over the default `DataFetcher`) but I am unsure if we want to do it at this point. Proper long term solution to get better support for those features would be to have Kotlin native GraphQL execution but that may not happen for the foreseeable  future.

Simplest workaround is to create custom data fetcher that properly extracts the value from the monad types - see https://github.com/ExpediaGroup/graphql-kotlin/pull/599 for example.

**Comment by smyrick** [comment] 2020-02-10 19:14
@johanflint As mentioned above you can support monos by overriding the `FunctionDataFetcher` used. See the documentation here: https://github.com/ExpediaGroup/graphql-kotlin/pull/599

Since any future changes would still require us to have you edit code in two places to support Mono, once for schema generation and once for execution, I don't see a better way to handle this than what is possible today. So I am going to close this issue.

**Closed by smyrick** 2020-02-10 19:14 UTC
Labels: type: bug

**Comment by johanflint** [comment] 2020-02-10 19:48
Thank you for responding so quickly and for clarifying the problem. Keep up the good work!
