### ISSUE TITLE
@GraphQLIgnore not detected on BeanFactoryAware

### ISSUE THREAD

**Issue by SJean-Marc** [ExpediaGroup/graphql-kotlin#655] opened 2020-04-09 07:35 UTC
**Library Version**
1.4.2, 2.0.0

**Describe the bug**
If you use a subquery with scope prototype and inject a singleton into it, we have no guarantee, it is destroyed properly, I was expecting to extend BeanFactoryAware in order to guarantee the proper destruction of the bean, but even with @GraphQLIgnore, the graphql process try to map the beanFactory element in the subquery class.

**To Reproduce**

```
@Component
class SubQueries : Query, BeanFactoryAware {
    private lateinit var beanFactory: BeanFactory

    @GraphQLIgnore
    override fun setBeanFactory(beanFactory: BeanFactory) {
        this.beanFactory = beanFactory
    }

    fun main(): SubQuery = beanFactory.getBean()
}

@Component
@Scope("prototype")
class SubQuery , BeanFactoryAware {

    @GraphQLIgnore
    private lateinit var beanFactory: BeanFactory

    @GraphQLIgnore
    override fun setBeanFactory(beanFactory: BeanFactory) {
        this.beanFactory = beanFactory
    }
    @Autowired
    @GraphQLIgnore
    lateinit var batRepo: batRepository
    fun secondary() : Long{
     return batRepository.findById(1).id
   }
}
```

**Expected behavior**
Exception is thrown, it should accept the graphQLIgnore

**Comment by smyrick** [comment] 2020-04-10 23:05
@SJean-Marc Can you verify one more time that you are matching my example: https://github.com/ExpediaGroup/graphql-kotlin/pull/657


You don't need to include `@GraphQLIgnore` if you can make a function or property non-public.

Can you also try making `batRepository` private

**Comment by smyrick** [comment] 2020-04-10 23:19
Ahh, ok I see the issue. It is the fact that you are trying to do multiple levels of `BeanFactoryAware` and we are picking up the interface. So the issue is not with `@GraphQLIgnore` but you will have to update your hooks to exclude that interface with `isValidSuperclass`

```kotlin
override fun isValidSuperclass(kClass: KClass<*>): Boolean {
        return when {
            kClass.isSubclassOf(BeanFactoryAware::class) -> false
            else -> super.isValidSuperclass(kClass)
        }
    }
```

@dariuszkuc Do you think we should just add that the list of default excluded interfaces?

**Comment by dariuszkuc** [comment] 2020-04-11 05:40
Sounds like the issue is due to attempt to build `BeanFactoryAware` interface which as you mentioned should be excluded in the hooks. Schema generator doesn't know anything about Spring so we won't be able to create default "blacklist".

Does the field gets excluded on the actual class? If not then that's a bug. Do we also need to validate whether implementing classes expose same fields as the interfaces? e.g. what happens when object ignores some fields from the interface?

**Comment by SJean-Marc** [comment] 2020-04-11 07:46
Thank you @smyrick and @dariuszkuc  for your answers. For now, the BeanFactoryAware field inherited is not excluded in the inherited subclasses. However, for instance on my others object when i use @GraphQLIgnore on the inherited object (and only if the mother object is scanned by graphQL process) it ignores the inherited field.
I will try to use your solution @smyrick thanks.

**Comment by SJean-Marc** [comment] 2020-04-11 13:16
@dariuszkuc the customHook doesn't fix my issue, do you have any other idea

**Comment by smyrick** [comment] 2020-04-13 20:59
I am not sure why that does not solve the issue @SJean-Marc as the example in the PR I have is working. Can you include a branch with the changes you are trying to test?

**Comment by smyrick** [comment] 2020-04-20 16:55
@SJean-Marc As our example app has a working example, I am going to close the issue. Feel free to comment here if you can reproduce an issue in our example app and share the code so we can test it out.

**Closed by smyrick** 2020-04-20 16:55 UTC
Labels: type: bug
