### ISSUE TITLE
Kotlin Boolean property without backing field is improperly resolved

### ISSUE THREAD

**Issue by undermark5** [ExpediaGroup/graphql-kotlin#987] opened 2021-01-04 21:36 UTC
**Library Version**
graphql-kotlin-spring-server:4.0.0-alpha.9

**Describe the bug**
Kotlin Boolean property without backing field is improperly resolved when the name starts with `is`

**To Reproduce**
Steps to reproduce the behavior. Please provide:

- Use the following class to define schema.
- Write a query that returns a single game object that requests `isFull`
- result is `The field at path <PATH> was declared a non null type, but the code involved in retrieving the data has wrongly returned a null value...`

```Kotlin
class Game(val numSeats : Int) {
    val players = mutableListOf<String>()
    val numSeats: Int get() players.size
    val isFull: Boolean get() = numPlayers == numSeats //The property isFull does not have a backing field
}
```
**Expected behavior**
the result should always properly retrieve a non null value.

**Suspected Cause**
I suspect this is something to do with how the Kotlin is compiled and the java code from graphql-java interacts with the Kotlin defined class. The method `getPropertyViaGetterMethod` in `graphql.schema.PropertyFetchingImpl` has some special logic when the field is a boolean type and searches for a getter by taking the field name and prepending `is` to it, which in the example above results in it searching for `isIsFull` which of course does not exist. In which case it tries to prepend the field name with `get` and search for that method, which again, does not exist. graphql-java utilizes the above method twice, first without forcing it to be accessible and then again with setting such methods to be accessible. In the situation above, becuase none of the methods it looks for exists, we fall back to the final attempt using `getPropertyViaFieldAccess`, which searches for fields of the given name, which in our case does not exist because Kotlin compiled the field to the java equivalent of `boolean isFull(){return numPlayers == numSeats}` which it misses entirely due to the fact that it searches for methods based on the field name prepended with either `is` or `get` even when such verbiage already exists in the field name. If instead of `val isFull: Boolean get() = numPlayers == numSeats` I use `var isFull: Boolean = false` and update it accordingly, then the result is the expected behavior due to the kotlin code compiling to the equivalent of a java class with a field isFull, however, this is less than ideal because it negates a key benefit of using Kotlin.

**Viable Workaround**
Until the issue is resolved, the ideal way to continue with the strengths of Kotlin code is to specify the JVM name for the method that retrieves the Kotlin field (I hesitate to say field because the java class does not contain such a field) via the `@JvmName()` annotation.
```Kotlin
class Game(val numSeats : Int) {
    val players = mutableListOf<String>()
    val numSeats: Int get() players.size
    val isFull: Boolean 
        @JvmName("getIsFull") //we still do not have a backing field,
        get() = numPlayers == numSeats //but we tell the compiler to use the name "getIsFull" for the compiled method
}
```
While this is a viable workaround of the issue, I have not seen such things documented as part of this library, and I believe that the should be.

**Summary**
This bug report is for an interesting bug that isn't so much a bug of graphql-kotlin, but rather a bug in how the java expects the class to be defined and how the kotlin class is seen from java. I propose that a PR be opened up for graphql-java that will check only prepend `is` or `get` if it is not already present in the name when searching via getter methods.

**Comment by dariuszkuc** [comment] 2021-01-04 21:41
This sounds like a duplicate of https://github.com/ExpediaGroup/graphql-kotlin/issues/529

**Comment by smyrick** [comment] 2021-01-04 22:08
This is a duplicate of #529, I will close and further discussion can happen there

**Closed by smyrick** 2021-01-04 22:08 UTC
Labels: type: bug
