### ISSUE TITLE
Kotlin Multiplatform with gradle plugin - Task with name 'compileKotlin' not found

### ISSUE THREAD

**Issue by Saturas89** [ExpediaGroup/graphql-kotlin#1139] opened 2021-05-06 10:55 UTC
Hello all,
I am trying to use the graphql-kotlin-client in my KMM project on server side (jvmMain) and
want to create the query objects with the latest gradle plugin com.expediagroup.graphql.
I cannot run any graphql gradle task.

`* What went wrong:
A problem occurred configuring root project 'my-project'.
> Could not create task ':graphqlGenerateClient'.
   > Task with name 'compileKotlin' not found in root project 'my-project'.`

I attached my build.gradle.kts
[build.txt](https://github.com/ExpediaGroup/graphql-kotlin/files/6433860/build.txt)

**Comment by smyrick** [comment] 2021-05-06 20:52
Duplicate of https://github.com/ExpediaGroup/graphql-kotlin/issues/876

**Closed by smyrick** 2021-05-06 20:52 UTC
Labels: type: bug

**Comment by smyrick** [comment] 2021-05-06 20:57
@Saturas89 We currently do not publish Kotlin Multiplatform artifacts. Your build file also indicates you are trying to use Kotlin 1.5 and we have not updated the library yet from 1.4
