### ISSUE TITLE
OptionalInput functionality breaks for deeply nested input parameters

### ISSUE THREAD

**Issue by natashashams** [ExpediaGroup/graphql-kotlin#954] opened 2020-12-01 20:17 UTC
**Library Version**
4.0.0-alpha.7 in graphql-kotlin-generator

**Describe the bug**
When using the OptionalInput wrapper on input parameters, I see that all deeply nested parameters show up as type OptionalInput.Defined (with value null) even though they were not explicitly defined in the graphql request.

**To Reproduce**
See "inputWithNestedOptionalValues" Test added to graphql-kotlin `OptionalInputTest.kt` 
here: https://github.com/natashashams/graphql-kotlin/commit/171439feedb2fd880b1a4ff62fd598793084f339

The test I added defines expected behavior, it is currently failing since actual behavior is something else.

**Expected behavior**
_Every_ input parameter that is wrapped with `Optionalnput` on schema definition should only be interpreted as `defined` on deserialization ONLY IF the input was explicitly defined in the query (ie is explicitly defined in DataFetchingEnvironment arguments). Otherwise, it should be interpreted as `undefined`.

**Comment by dariuszkuc** [comment] 2020-12-20 03:57
Thanks for raising this but after looking into this I am unsure whether the issue is with `jackson-databind`, `jackson-module-kotlin` or with the serializer code in the `graphql-kotlin`. TLDR -> as a workaround initialize the optional fields to `Undefined`.

--- Long Story
The underlying issue is that when we evaluate deserialization context to check whether we are processing a field (i.e. [OptionalInput:L69](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/OptionalInput.kt#L69)) it only works for root fields. When we evaluate it for the undefined optional arguments it still points to a parent node which has a field name associated with it and which in turn fails the condition check.

I was trying to reproduce this Jackson behavior in plain Java (which would be requested by if this is a bug in `jackson-databind`) but was unable to. When I re-created my data classes with both default and non-default constructors I was hitting an issue that undefined fields were never attempted to deserialize and were initialized to `null`. Specifying default UNDEFINED value for those fields worked fine.

I've added a test case in https://github.com/ExpediaGroup/graphql-kotlin/pull/976 to verify this behavior.

**Comment by dariuszkuc** [comment] 2021-01-09 04:34
Closing issue with the suggested workaround to specify default values (UNDEFINED) for each optional input fields

**Closed by dariuszkuc** 2021-01-09 04:34 UTC
Labels: type: bug
